services:

  postgres_db:
    image: postgres:15.0-alpine
    command: postgres -c 'max_connections=5000'
    restart: on-failure
    volumes:
      - ./.postgres_data/:/var/lib/postgresql/data
    ports:
      - "5445:5432"
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: go-stateflow
      POSTGRES_DB: go-stateflow
      POSTGRES_HOST_AUTH_METHOD: trust

  engine:
    restart: on-failure
    ports:
      - "2140:2140"
    depends_on:
      - postgres_db
    build:
      dockerfile: ./Dockerfile

  blogs:
    ports:
      - "5003:5003"
    build:
      context: ./examples/services/blogs
      dockerfile: Dockerfile

  payments:
    ports:
      - "5002:5002"
    build:
      context: ./examples/services/payments
      dockerfile: Dockerfile

  notifications:
    ports:
      - "5001:5001"
    build:
      context: ./examples/services/notifications
      dockerfile: Dockerfile