grpc_port: 2140
scenarios_path: ../scenarios
database:
  host: localhost
  user: go-stateflow
  name: go-stateflow
  password: qwerty
  port: 5445
  ssl_mode: disable
  max_open_connections: 20
  max_idle_connections: 20
  auto_migrate: true
handlers:
  notifications:
    host: localhost
    port: 5001
  orders:
    host: localhost
    port: 5002
async_worker:
  count: 3
  instances_batch_size: 30
  instance_fetching_interval: 3s
  instance_lock_timeout: 20s
  locker_id: 'main_node'