grpc_port: 2140
scenarios_path: ./scenarios
database:
  host: postgres_db
  user: go-stateflow
  name: go-stateflow
  password: qwerty
  port: 5432
  ssl_mode: disable
  max_open_connections: 20
  max_idle_connections: 20
  auto_migrate: true
handlers:
  notifications:
    host: notifications
    port: 5001
  payments:
    host: payments
    port: 5002
  blogs:
    host: blogs
    port: 5003
async_worker:
  count: 3
  instances_batch_size: 30
  instance_fetching_interval: 5s
  instance_lock_timeout: 5s
  locker_id: 'main_node'